### ISSUE TITLE
Nice job using divs to organize your code!

### ISSUE THREAD

**Issue by jzhu01** [gray1223/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/gray1223/prj-rev-bwfs-dasmoto/blob/117b04729c2798981cab8360ee35ab186addcab2/Dasmotos/index.html#L11-L20

I like how you chose to use divs here to organize your code. It makes it look very clean and easy to read. 😊

**Comment by gray1223** [comment]
Thank you, I appreciate it!
