### ISSUE TITLE
Suggestion - no need to use font-weight:bold on headings

### ISSUE THREAD

**Issue by jzhu01** [gray1223/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/gray1223/prj-rev-bwfs-dasmoto/blob/117b04729c2798981cab8360ee35ab186addcab2/Dasmotos/resources/style.css#L20

Since headings are actually bolded by default here, we don't need to specify it.

**Comment by gray1223** [comment]
Roger that.
